### ISSUE TITLE
Add monitoring for Pungi nodes

### ISSUE THREAD

**Issue by zklevsha** [AlmaLinux/albs-infra#4]
We have four hosts which contains two Docker container with Pungi stuff per each host. And we need monitoring for them.

**For hosts we need to check the following items:**
- A host availability by SSH
- Working Nginx (check 80 port). Check it by URL http://<domain_name>/almalinux
- The last execution time of sync timer reposync.x86_64.timer was less than day ago. The arch suffix is different for all hosts (according to their architecture)
- The sync service was ran and finished successfully
- Systemd service openvpn-client@al.service is running and you can WGET/CURL http://172.28.29.85:8080/

**For Docker containers we need to check the following items**
- A Docker container is available by SSH (port 6023 for AL8 and 6022 for AL9)
- The process `java -jar /root/jenkins/agent.jar -jnlpUrl http://172.28.29.85:8080/computer/AL<version><arch>/jenkins-agent.jnlp -secret @/root/jenkins/agent.secret-file -workDir /root/jenkins` is running inside a container. There are <version> is 9 or 8, <arch> is host’s architecture in upper case.

Domain names (8 and 9 points to the same host):
- aarch64-pungi-8.almalinux.org and aarch64-pungi-9.almalinux.org, user - soksanichenko
- x86_64-pungi-8.almalinux.org and x86_64-pungi-9.almalinux.org, user - almabuilder
- ppc64le-pungi-8.almalinux.org and ppc64le-pungi-9.almalinux.org, user - almabuilder
- s390x-pungi-8.almalinux.org and s390x-pungi-9.almalinux.org, user - almabuilder

Docker containers names:

- pungi_build_node_almalinux_9_aarch64 and pungi_build_node_almalinux_8_aarch64
- pungi_build_node_almalinux_9_x86_64 and pungi_build_node_almalinux_8_x86_64
- pungi_build_node_almalinux_9_ppc64le and pungi_build_node_almalinux_8_ppc64le
- pungi_build_node_almalinux_9_s390x and pungi_build_node_almalinux_8_s390x

And I need separate channel in the Slack for notifications, together with notifications from task AL-5231

**Comment by zklevsha** [comment]
DNS to hostname

- aarch64-pungi-8.almalinux.org / aarch64-pungi-9.almalinux.org -> arm64-builder04.almalinux.org (has monitoring)
- x86_64-pungi-8.almalinux.org / x86_64-pungi-9.almalinux.org -> alukoshko-x86-build.almalinux.org (no monitoring)
- ppc64le-pungi-8.almalinux.org / ppc64le-pungi-9.almalinux.org -> ppc64le-pungi.almalinux.org.novalocal (no monitoring)
- s390x-pungi-8.almalinux.org / s390x-pungi-9.almalinux.org -> s390x-builder01.almalinux.org (has monitoring)

**Comment by zklevsha** [comment]
[Hosts in Zabbix](https://zabbix.almalinux.org/zabbix.php?name=&ip=&dns=&port=&status=-1&evaltype=0&tags%5B0%5D%5Btag%5D=&tags%5B0%5D%5Boperator%5D=0&tags%5B0%5D%5Bvalue%5D=&maintenance_status=1&filter_name=&filter_show_counter=0&filter_custom_time=0&sort=name&sortorder=ASC&show_suppressed=0&action=host.view&groupids%5B%5D=32)

[Grafana dashboard](https://build.almalinux.org/grafana/d/bc87643a-eecb-40d0-90f2-bd6505c032da/pungi-hosts?orgId=1&refresh=1m)

@soksanichenko could you please look at my solution?

**Comment by soksanichenko** [comment]
@zklevsha I see it works fine in Grafana, but I don't see the Pungi hosts in Zabbix (look at the screenshot) 
![image](https://github.com/AlmaLinux/albs-infra/assets/50624082/6b9ce9ca-a9b8-49d7-8682-bf5c75c6a315)

**Comment by zklevsha** [comment]
@soksanichenko permissions issues,
Please relogin and check now

**Comment by soksanichenko** [comment]
Yeah, works fine. Thank you!
